name: ci

on:
  push:
    branches:
      - 'main'
  create:
    tags:
      - "*"

jobs:
  docker:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
#    principalSet://iam.googleapis.com/projects/681636924832/locations/global/workloadIdentityPools/github-actions-pool/github-provider
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
          service_account: ${{secrets.SERVICE_ACCOUNT}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GCR
        uses: docker/login-action@v2
        with:
          registry: us.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Build and push
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: us.gcr.io/telvanni-platform/hello-world-service:${{env.GITHUB_REF_NAME}}